# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-06 14:39
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0004_auto_20160605_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_fk', models.PositiveIntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
                ('town_village', models.CharField(blank=True, max_length=100, null=True)),
                ('street_address', models.CharField(blank=True, max_length=100, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='AddressType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'address_type',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_fk', models.PositiveIntegerField(blank=True, null=True)),
                ('value_text', models.TextField(blank=True, null=True)),
                ('orderby', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('contact_type_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'contact_type',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_fk', models.PositiveIntegerField(blank=True, null=True)),
                ('subject_type_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.NullBooleanField()),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.NullBooleanField()),
                ('employee_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='arhitektuurkolm.Employee')),
            ],
            options={
                'db_table': 'employee_role',
            },
        ),
        migrations.CreateModel(
            name='EmployeeRoleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'employee_role_type',
            },
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('full_name', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ent_created_by', to='arhitektuurkolm.Employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ent_updated_by', to='arhitektuurkolm.Employee')),
            ],
            options={
                'db_table': 'enterprise',
            },
        ),
        migrations.CreateModel(
            name='EnterprisePersonRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'enterprise_person_relation',
            },
        ),
        migrations.CreateModel(
            name='EntPerRelationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'ent_per_relation_type',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('identity_code', models.CharField(blank=True, max_length=20, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pers_created_by', to='arhitektuurkolm.Employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pers_updated_by', to='arhitektuurkolm.Employee')),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='StructUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upper_unit_fk', models.PositiveIntegerField(blank=True, null=True)),
                ('level', models.PositiveIntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('enterprise_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='arhitektuurkolm.Enterprise')),
            ],
            options={
                'db_table': 'struct_unit',
            },
        ),
        migrations.CreateModel(
            name='SubjectAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_fk', models.PositiveIntegerField(blank=True, null=True)),
                ('orderby', models.IntegerField(blank=True, null=True)),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('data_type', models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True)),
            ],
            options={
                'db_table': 'subject_attribute',
            },
        ),
        migrations.CreateModel(
            name='SubjectAttributeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(blank=True, max_length=200, null=True)),
                ('data_type', models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True)),
                ('orderby', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('required', models.NullBooleanField()),
                ('multiple_attributes', models.NullBooleanField()),
                ('created_by_default', models.NullBooleanField(default=True)),
            ],
            options={
                'db_table': 'subject_attribute_type',
            },
        ),
        migrations.CreateModel(
            name='SubjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'subject_type',
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('password_never_expires', models.NullBooleanField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_created_by', to='arhitektuurkolm.Employee')),
                ('subject_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_emp', to='arhitektuurkolm.Employee')),
                ('subject_type_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='arhitektuurkolm.SubjectType')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_account',
            },
        ),
        migrations.AddField(
            model_name='subjectattributetype',
            name='subject_type_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='arhitektuurkolm.SubjectType'),
        ),
        migrations.AddField(
            model_name='subjectattribute',
            name='subject_attribute_type_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='arhitektuurkolm.SubjectAttributeType'),
        ),
        migrations.AddField(
            model_name='subjectattribute',
            name='subject_type_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='enterprisepersonrelation',
            name='ent_per_relation_type_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='arhitektuurkolm.EntPerRelationType'),
        ),
        migrations.AddField(
            model_name='enterprisepersonrelation',
            name='enterprise_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='arhitektuurkolm.Enterprise'),
        ),
        migrations.AddField(
            model_name='enterprisepersonrelation',
            name='person_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='arhitektuurkolm.Person'),
        ),
        migrations.AddField(
            model_name='employeerole',
            name='employee_role_type_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='arhitektuurkolm.EmployeeRoleType'),
        ),
        migrations.AddField(
            model_name='employee',
            name='enterprise_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='arhitektuurkolm.Enterprise'),
        ),
        migrations.AddField(
            model_name='employee',
            name='person_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='arhitektuurkolm.Person'),
        ),
        migrations.AddField(
            model_name='employee',
            name='struct_unit_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='arhitektuurkolm.StructUnit'),
        ),
        migrations.AddField(
            model_name='contact',
            name='subject_type_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='arhitektuurkolm.SubjectType'),
        ),
        migrations.AddField(
            model_name='address',
            name='address_type_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='arhitektuurkolm.AddressType'),
        ),
        migrations.AddField(
            model_name='address',
            name='subject_type_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
